### ISSUE TITLE
Code and tag missing for 0.3.0 release

### ISSUE THREAD

**Issue by noirbizarre** [mvantellingen/wagtail-factories#4]
Hi !

https://pypi.python.org/pypi/wagtail-factories inidcate that current version is 0.3.0 and released on 2017-05-16 and this repository latest commit date is 2017-05-10 and latest tag is `0.2.0` so it seems that last commits and tag (and `CHANGES` have not been pushed to this repository.

**Comment by mvantellingen** [comment]
done
